name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Update version in project
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        $csproj = "AddToPath.csproj"
        $xml = [xml](Get-Content $csproj)
        $xml.Project.PropertyGroup.Version = $version
        $xml.Save($csproj)
      shell: pwsh
    
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: true
        prerelease: false
        body: |
          Release ${{ steps.get_version.outputs.VERSION }}
          
          Changes in this release:
          - Please update release notes here
          
    - name: Upload Release Asset - EXE
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/Release/net472/AddToPath.exe
        asset_name: AddToPath.exe
        asset_content_type: application/octet-stream
        
    - name: Upload Release Asset - Config
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/Release/net472/AddToPath.exe.config
        asset_name: AddToPath.exe.config
        asset_content_type: application/xml
